# Generated by Django 3.2.8 on 2023-03-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectusers',
            new_name='users',
        ),
    ]
